import { createBrowserRouter } from 'react-router';
import { Layout } from './components/Layout';
import { Home } from './components/Home';
import { ProjectDetails } from './components/ProjectDetails';
import { GithubPages } from './components/GithubPages';
import { PersonalPages } from './components/PersonalPages';
import { AssignmentsPage } from './components/AssignmentsPage';
import { PersonalPagesContent } from './components/PersonalPagesContent';
import { ProjectsPage } from './components/ProjectsPage';
import { AboutPage } from './components/AboutPage';
import { InterestsPage } from './components/InterestsPage';
import { PortfolioPage } from './components/PortfolioPage';
import { USCLifePage } from './components/USCLifePage';
import { VitaePage } from './components/VitaePage';
import { GreenvillePage } from './components/GreenvillePage';
import { PublicationsPage } from './components/PublicationsPage';
import { AwardsPage } from './components/AwardsPage';
import { CertificationsPage } from './components/CertificationsPage';
import { PictureWallPage } from './components/PictureWallPage';
import { TrophiesPage } from './components/TrophiesPage';
import { MandATransactionsPage } from './components/MandATransactionsPage';
import { CapitolTechnologyPage } from './components/CapitolTechnologyPage';
import { UniversityOfSouthCarolinaPage } from './components/UniversityOfSouthCarolinaPage';
import { UniversityOfPennsylvaniaPage } from './components/UniversityOfPennsylvaniaPage';
import { UniversityOfMichiganPage } from './components/UniversityOfMichiganPage';
import { UniversityOfDelawarePage } from './components/UniversityOfDelawarePage';
import { UNCWilmingtonPage } from './components/UNCWilmingtonPage';
import { UniversityOfTexasPage } from './components/UniversityOfTexasPage';
import { OldDominionUniversityPage } from './components/OldDominionUniversityPage';
import { WilliamAndMaryPage } from './components/WilliamAndMaryPage';
import { Assignment1 } from './components/assignments/Assignment1';
import { Assignment2 } from './components/assignments/Assignment2';
import { Assignment3 } from './components/assignments/Assignment3';
import { Assignment4 } from './components/assignments/Assignment4';
import { Assignment5 } from './components/assignments/Assignment5';
import { Assignment6 } from './components/assignments/Assignment6';
import { Assignment7 } from './components/assignments/Assignment7';
import { Assignment8 } from './components/assignments/Assignment8';
import { Assignment9 } from './components/assignments/Assignment9';
import { Assignment10 } from './components/assignments/Assignment10';
import { Phase1 } from './components/projects/Phase1';
import { Phase2 } from './components/projects/Phase2';
import { Phase3 } from './components/projects/Phase3';
import { Phase4 } from './components/projects/Phase4';
import { Phase5 } from './components/projects/Phase5';
import { Phase6 } from './components/projects/Phase6';
import { Phase7 } from './components/projects/Phase7';
import { Phase8 } from './components/projects/Phase8';
import { Phase9 } from './components/projects/Phase9';
import { Phase10 } from './components/projects/Phase10';
import { DocumentsPage } from './components/DocumentsPage';
import { SettingsPage } from './components/SettingsPage';
import { LoginPage } from './components/LoginPage';
import { SocialLoginPage } from './components/SocialLoginPage';
import { RegisterPage } from './components/RegisterPage';
import { ReportsPage } from './components/ReportsPage';
import { ReleasesPage } from './components/ReleasesPage';
import { TeamPage } from './components/TeamPage';
import { MilestonesPage } from './components/MilestonesPage';
import { MyProjectsPage } from './components/MyProjectsPage';
import { VisitorRegisterPage } from './components/VisitorRegisterPage';
import { CarePage } from './components/CarePage';

export const router = createBrowserRouter([
  {
    path: '/',
    Component: Layout,
    children: [
      { index: true, Component: Home },
      { path: 'my-projects', Component: MyProjectsPage },
      { path: 'render-react-info', Component: ProjectDetails },
      { path: 'github-pages', Component: GithubPages },
      { path: 'personal-pages', Component: PersonalPagesContent },
      { path: 'personal-pages/about', Component: AboutPage },
      { path: 'personal-pages/interests', Component: InterestsPage },
      { path: 'personal-pages/portfolio', Component: PortfolioPage },
      { path: 'personal-pages/usclife', Component: USCLifePage },
      { path: 'personal-pages/vitae', Component: VitaePage },
      { path: 'personal-pages/greenville', Component: GreenvillePage },
      { path: 'personal-pages/publications', Component: PublicationsPage },
      { path: 'personal-pages/awards', Component: AwardsPage },
      { path: 'personal-pages/certifications', Component: CertificationsPage },
      { path: 'personal-pages/picturewall', Component: PictureWallPage },
      { path: 'personal-pages/trophies', Component: TrophiesPage },
      { path: 'personal-pages/matransactions', Component: MandATransactionsPage },
      { path: 'personal-pages/capitoltechnology', Component: CapitolTechnologyPage },
      { path: 'personal-pages/usc', Component: UniversityOfSouthCarolinaPage },
      { path: 'personal-pages/upenn', Component: UniversityOfPennsylvaniaPage },
      { path: 'personal-pages/umich', Component: UniversityOfMichiganPage },
      { path: 'personal-pages/udel', Component: UniversityOfDelawarePage },
      { path: 'personal-pages/uncw', Component: UNCWilmingtonPage },
      { path: 'personal-pages/utexas', Component: UniversityOfTexasPage },
      { path: 'personal-pages/odu', Component: OldDominionUniversityPage },
      { path: 'personal-pages/wm', Component: WilliamAndMaryPage },
      { path: 'assignments', Component: AssignmentsPage },
      { path: 'assignments/1', Component: Assignment1 },
      { path: 'assignments/2', Component: Assignment2 },
      { path: 'assignments/3', Component: Assignment3 },
      { path: 'assignments/4', Component: Assignment4 },
      { path: 'assignments/5', Component: Assignment5 },
      { path: 'assignments/6', Component: Assignment6 },
      { path: 'assignments/7', Component: Assignment7 },
      { path: 'assignments/8', Component: Assignment8 },
      { path: 'assignments/9', Component: Assignment9 },
      { path: 'assignments/10', Component: Assignment10 },
      { path: 'projects', Component: ProjectsPage },
      { path: 'projects/1', Component: Phase1 },
      { path: 'projects/2', Component: Phase2 },
      { path: 'projects/3', Component: Phase3 },
      { path: 'projects/4', Component: Phase4 },
      { path: 'projects/5', Component: Phase5 },
      { path: 'projects/6', Component: Phase6 },
      { path: 'projects/7', Component: Phase7 },
      { path: 'projects/8', Component: Phase8 },
      { path: 'projects/9', Component: Phase9 },
      { path: 'projects/10', Component: Phase10 },
      { path: 'documents', Component: DocumentsPage },
      { path: 'settings', Component: SettingsPage },
      { path: 'login', Component: SocialLoginPage },
      { path: 'api-login', Component: LoginPage },
      { path: 'register', Component: RegisterPage },
      { path: 'reports', Component: ReportsPage },
      { path: 'releases', Component: ReleasesPage },
      { path: 'team', Component: TeamPage },
      { path: 'milestones', Component: MilestonesPage },
      { path: 'visitor-register', Component: VisitorRegisterPage },
      { path: 'care', Component: CarePage },
    ],
  },
]);
